### PR TITLE
Added length limitation to 20 characters long -- Added media queries so the website is responsive 

### PR DESCRIPTION
**Pull request by abitsalihu**
I added the logic that if the input value of the characters is less than 20 then an error message will be displayed that the password will not be rendered because it will have problems.

I have Implemented media queries so the page can be responsive through all devices.

Below are videos that showcase the length limitation logic also the page responsiveness.

`Mobile size:`

https://user-images.githubusercontent.com/94648837/210279256-422e6167-b383-4ce4-9539-2af9e6feed43.mov

`Desktop size:`

https://user-images.githubusercontent.com/94648837/210279277-a2349295-78b6-43d3-812d-456cb15dbda9.mov

### CODE REVIEW

**Review by aondodawid — COMMENTED** [review]
Great job

**Review by aondodawid — APPROVED** [review]
Change approved great job

**Comment by abitsalihu** [comment]
Hey @aondodawid, thanks for having me. I would love it if we could connect on LinkedIn --
https://www.linkedin.com/in/abit-s/

**Comment by aondodawid** [comment]
:-) I don't have yet but when i make account u will be first person to add

śr., 4.01.2023, 19:47 użytkownik Abit Salihu ***@***.***>
napisał:

**Comment by abitsalihu** [comment]
@aondodawid, alright glad to hear that.

**Pull request merged**
